export const SET_USER = 'SET_USER';

export const INITIALIZE_PLAYER = 'INITIALIZE_PLAYER';

export const PLAYER_PLAY = 'PLAYER_PLAY';
export const PLAYER_PAUSE = 'PLAYER_PAUSE';

export const SONG_INFO_FOCUS = 'SONG_INFO_FOCUS';
export const SONG_INFO_BLUR = 'SONG_INFO_BLUR';

export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';

export const SEARCH_BAR_FOCUS = 'SEARCH_BAR_FOCUS';
export const SEARCH_BAR_BLUR = 'SEARCH_BAR_BLUR';

export const SET_CURRENT_SONG_INFO = 'SET_CURRENT_SONG_INFO';
