export const SET_USER = 'SET_USER';

export const SET_PLAYER = 'SET_PLAYER';

export const PLAYER_PLAY = 'PLAYER_PLAY';
export const PLAYER_PAUSE = 'PLAYER_PAUSE';

export const SONG_INFO_FOCUS = 'SONG_INFO_FOCUS';
export const SONG_INFO_BLUR = 'SONG_INFO_BLUR';

export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
