export const SET_USER = 'SET_USER';

export const INITIALIZE_PLAYER = 'INITIALIZE_PLAYER';

export const PLAYER_PLAY = 'PLAYER_PLAY';
export const PLAYER_PAUSE = 'PLAYER_PAUSE';

export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';

export const SEARCH_BAR_FOCUS = 'SEARCH_BAR_FOCUS';
export const SEARCH_BAR_BLUR = 'SEARCH_BAR_BLUR';

export const SET_CURRENTLY_PLAYING = 'SET_CURRENTLY_PLAYING';
export const SET_LOOP_STATUS = 'SET_LOOP_STATUS';
